routes:
  /: 
    template: coming-soon
    data: page.coming-soon
  
collections:
  /videos/:
    permalink: /videos/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
